# Generated by Django 3.2.8 on 2022-04-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('gurdian_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=11)),
                ('whatsapp', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('school_college_name', models.CharField(max_length=50)),
                ('appearing_passed_12', models.BooleanField(null=True)),
                ('board_name', models.CharField(max_length=10)),
                ('appeared_wbjee_jeeMain', models.BooleanField(null=True)),
            ],
        ),
    ]
