# Generated by Django 3.2.8 on 2022-04-09 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2022, 4, 9, 13, 45, 30, 516708)),
        ),
    ]
