# Generated by Django 3.2.8 on 2022-04-09 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_student_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2022, 4, 9, 13, 46, 12, 322501)),
        ),
    ]
