# Generated by Django 3.2.8 on 2022-04-09 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_alter_student_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='appearing_passed_12',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2022, 4, 9, 13, 53, 55, 76408)),
        ),
    ]
