# Generated by Django 3.2.8 on 2022-04-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0004_auto_20220409_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateField(),
        ),
    ]
