# Generated by Django 3.2.8 on 2022-05-26 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0011_auto_20220526_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 14, 39, 2, 579372)),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_seen',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True),
        ),
    ]
