# Generated by Django 3.2.8 on 2022-04-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0011_auto_20220410_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('start_time', models.IntegerField(blank=True, null=True)),
                ('exam_duration', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
