# Generated by Django 3.2.8 on 2022-04-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0012_detailsexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsexam',
            name='date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='detailsexam',
            name='exam_duration',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='detailsexam',
            name='month',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='detailsexam',
            name='start_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
