# Generated by Django 3.2.8 on 2022-04-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0013_auto_20220410_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsexam',
            name='total_questions',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
