# Generated by Django 3.2.8 on 2022-04-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0016_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
