# Generated by Django 3.2.8 on 2022-04-11 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0017_alter_rules_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rules',
        ),
    ]
