# Generated by Django 3.2.8 on 2022-04-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0018_delete_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
    ]
