# Generated by Django 3.2.8 on 2022-04-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0021_choosedoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choosedoptions',
            name='userid',
        ),
    ]
