# Generated by Django 3.2.8 on 2022-04-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0022_remove_choosedoptions_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='choosedoptions',
            name='userid',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
