# Generated by Django 3.2.8 on 2022-04-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0023_choosedoptions_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsexam',
            name='registration_last_date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
