# Generated by Django 3.2.8 on 2022-04-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0025_detailsexam_registration_last_month'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoosedOptions',
        ),
    ]
