# Generated by Django 3.2.8 on 2022-04-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0027_choosedoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choosedoptions',
            name='id',
        ),
        migrations.AlterField(
            model_name='choosedoptions',
            name='questionNumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
