# Generated by Django 3.2.8 on 2022-04-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0028_auto_20220420_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoosedOptions',
        ),
    ]
