# Generated by Django 3.2.8 on 2022-04-20 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholarship', '0029_delete_choosedoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoosedOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default=None, max_length=100)),
                ('questionNumber', models.CharField(max_length=5)),
                ('selectedOption', models.CharField(max_length=5)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
