# Generated by Django 3.2.8 on 2022-04-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0030_choosedoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='choosedoptions',
            name='checkedStatus',
            field=models.BooleanField(default=False),
        ),
    ]
