# Generated by Django 3.2.8 on 2022-04-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0031_choosedoptions_checkedstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exam_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='last_seen',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
