# Generated by Django 3.2.8 on 2022-04-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0033_remove_choosedoptions_checkedstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
