# Generated by Django 3.2.8 on 2022-05-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0035_auto_20220428_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsexam',
            name='start_min',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
