# Generated by Django 4.0 on 2022-05-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0037_rename_result_result2'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_feedback',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
